create table sys_permission (id bigint generated by default as identity, description varchar(120), name varchar(120) not null, parent_id bigint, url varchar(120) not null, primary key (id));
create table sys_role (id bigint generated by default as identity, name varchar(10) not null, primary key (id));
create table sys_role_permission (role_id bigint not null, permission_id bigint not null, primary key (role_id, permission_id));
create table sys_user (id bigint generated by default as identity, password varchar(32) not null, username varchar(32) not null, primary key (id));
create table sys_user_role (user_id bigint not null, role_id bigint not null, primary key (user_id, role_id));

alter table sys_permission drop constraint if exists uk_sys_permission__name;
alter table sys_permission add constraint uk_sys_permission__name unique (name);

alter table sys_permission drop constraint if exists uk_sys_permission__url;
alter table sys_permission add constraint uk_sys_permission__url unique (url);

alter table sys_role drop constraint if exists uk_sys_role__name;
alter table sys_role add constraint uk_sys_role__name unique (name);

alter table sys_user drop constraint if exists uk_sys_user__username;
alter table sys_user add constraint uk_sys_user__username unique (username);

-- 添加外键
alter table sys_user_role drop constraint if exists fk_sys_user_role__user_id;
alter table sys_user_role
    add constraint fk_sys_user_role__user_id
    foreign key (user_id)
    references sys_user(id)
    -- 级联更新，级联删除
    on update cascade
    on delete cascade
    ;

alter table sys_user_role drop constraint if exists fk_sys_user_role__role_id;
alter table sys_user_role
    add constraint fk_sys_user_role__role_id
    foreign key (role_id)
    references sys_role(id)
    on update cascade
    on delete cascade
    ;

alter table sys_role_permission drop constraint if exists fk_sys_role_permission__role_id;
alter table sys_role_permission
    add constraint fk_sys_role_permission__role_id
    foreign key (role_id)
    references sys_role(id)
    on update cascade
    on delete cascade
    ;

alter table sys_role_permission drop constraint if exists fk_sys_role_permission__permission_id;
alter table sys_role_permission
    add constraint fk_sys_role_permission__permission_id
    foreign key (permission_id)
    references sys_permission(id)
    on update cascade
    on delete cascade
    ;

alter table sys_permission drop constraint if exists fk_sys_permission__parent_id;
alter table sys_permission
    add constraint fk_sys_permission__parent_id
    foreign key (parent_id)
    references sys_permission(id)
    on update cascade
    on delete cascade
    ;
