DELETE FROM AB01 WHERE 1=1;

INSERT INTO AB01(id, AAB002, AAB003)
VALUES (10, 'ACCOUNTING', 'NEW YORK'),
       (20, 'RESEARCH', 'DALLAS'),
       (30, 'SALES', 'CHICAGO'),
       (40, 'OPERATIONS', 'BOSTON');

