server:
  port: 1234
  servlet:
    context-path: /demo

# DataSource Config
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    schema: classpath:db/schema-h2.sql
#    data: classpath:db/data-h2.sql
#    url: jdbc:mysql://localhost:3306/test
#    username: root
#    password: Root123456

spring:
  # ShardingSphere 配置项
  shardingsphere:
    datasource:
      # 所有数据源的名字
      names: test, test1
      test:
        type: com.zaxxer.hikari.HikariDataSource # 使用 Hikari 数据库连接池
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/test
        username: root
        password:

      test1:
        type: com.zaxxer.hikari.HikariDataSource # 使用 Hikari 数据库连接池
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/test1
        username: root
        password:
    # 分片规则
    sharding:
      tables:
        # ################## 垂直分库的表 ######################
        ac01:
          actualDataNodes: test.ac01

        ab01:
          actualDataNodes: test.ab01
        # 如上，ac01和ab01都位于同一个库test中，所以是可以做联合查询的
        ad01:
          actualDataNodes: test1.ad01
        # ################## 垂直分库的表 ######################
    # 拓展属性配置
    props:
      sql:
        show: true # 打印 SQL


mybatis:
  # 扫描xml的位置
  mapper-locations: classpath:/mappers/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    # mybatis开启缓存
    cache-enabled: true

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation:
                  RequestMappingHandlerMapping: trace
