drop database if exists test0;
create database test0;

use test0;

DROP TABLE IF EXISTS AB01_0;

CREATE TABLE AB01_0
(
    id BIGINT(20)  NOT NULL AUTO_INCREMENT COMMENT '部门编号',
    aab001 BIGINT(20),
    AAB002 VARCHAR(30) NOT NULL COMMENT '部门名称',
    AAB003 VARCHAR(30) NOT NULL COMMENT '部门所在位置',
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS AB01_2;

CREATE TABLE AB01_2
(
    id BIGINT(20)  NOT NULL AUTO_INCREMENT COMMENT '部门编号',
    aab001 BIGINT(20),
    AAB002 VARCHAR(30) NOT NULL COMMENT '部门名称',
    AAB003 VARCHAR(30) NOT NULL COMMENT '部门所在位置',
    PRIMARY KEY (id)
);
DROP TABLE IF EXISTS AB01_4;

CREATE TABLE AB01_4
(
    id BIGINT(20)  NOT NULL AUTO_INCREMENT COMMENT '部门编号',
    aab001 BIGINT(20),
    AAB002 VARCHAR(30) NOT NULL COMMENT '部门名称',
    AAB003 VARCHAR(30) NOT NULL COMMENT '部门所在位置',
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS AB01_6;

CREATE TABLE AB01_6
(
    id BIGINT(20)  NOT NULL AUTO_INCREMENT COMMENT '部门编号',
    aab001 BIGINT(20),
    AAB002 VARCHAR(30) NOT NULL COMMENT '部门名称',
    AAB003 VARCHAR(30) NOT NULL COMMENT '部门所在位置',
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS AB01_8;

CREATE TABLE AB01_8
(
    id BIGINT(20)  NOT NULL AUTO_INCREMENT COMMENT '部门编号',
    aab001 BIGINT(20),
    AAB002 VARCHAR(30) NOT NULL COMMENT '部门名称',
    AAB003 VARCHAR(30) NOT NULL COMMENT '部门所在位置',
    PRIMARY KEY (id)
);

drop database if exists test1;
create database test1;
use test1;
DROP TABLE IF EXISTS AB01_1;

  CREATE TABLE AB01_1
  (
      id BIGINT(20)  NOT NULL AUTO_INCREMENT COMMENT '部门编号',
    aab001 BIGINT(20),
      AAB002 VARCHAR(30) NOT NULL COMMENT '部门名称',
      AAB003 VARCHAR(30) NOT NULL COMMENT '部门所在位置',
      PRIMARY KEY (id)
  );

DROP TABLE IF EXISTS AB01_3;

CREATE TABLE AB01_3
(
    id BIGINT(20)  NOT NULL AUTO_INCREMENT COMMENT '部门编号',
    aab001 BIGINT(20),
    AAB002 VARCHAR(30) NOT NULL COMMENT '部门名称',
    AAB003 VARCHAR(30) NOT NULL COMMENT '部门所在位置',
    PRIMARY KEY (id)
);
DROP TABLE IF EXISTS AB01_5;

CREATE TABLE AB01_5
(
    id BIGINT(20)  NOT NULL AUTO_INCREMENT COMMENT '部门编号',
    aab001 BIGINT(20),
    AAB002 VARCHAR(30) NOT NULL COMMENT '部门名称',
    AAB003 VARCHAR(30) NOT NULL COMMENT '部门所在位置',
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS AB01_7;

CREATE TABLE AB01_7
(
    id BIGINT(20)  NOT NULL AUTO_INCREMENT COMMENT '部门编号',
    aab001 BIGINT(20),
    AAB002 VARCHAR(30) NOT NULL COMMENT '部门名称',
    AAB003 VARCHAR(30) NOT NULL COMMENT '部门所在位置',
    PRIMARY KEY (id)
);
DROP TABLE IF EXISTS AB01_9;

CREATE TABLE AB01_9
(
    id BIGINT(20)  NOT NULL AUTO_INCREMENT COMMENT '部门编号',
    aab001 BIGINT(20),
    AAB002 VARCHAR(30) NOT NULL COMMENT '部门名称',
    AAB003 VARCHAR(30) NOT NULL COMMENT '部门所在位置',
    PRIMARY KEY (id)
);

