server:
  port: 1234
  servlet:
    context-path: /demo

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation:
                  RequestMappingHandlerMapping: trace

ss:
  loginProcessingUrl: /doLogin
  logoutUrl: /doLogout
  usernameParameter: username
  passwordParameter: password
  codeParameter: code

jwt:
  tokenHeader: Authorization
  tokenPrefix: "Bearer "
  expiration: 300
