server:
  port: 1234
  servlet:
    context-path: /demo

debug: false

# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    schema: classpath:db/schema-mysql.sql
    data: classpath:db/data-mysql.sql
    url: jdbc:mysql://127.0.0.1:3306/rbac?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Root123456

mybatis-plus:
  # 扫描xml的位置
  mapper-locations:
    - classpath:/mappers/**/*Mapper.xml
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
  global-config:
    # 驼峰下划线转换
    db-column-underline: true

logging:
  level:
    com:
      example:
        lewjun:
          # 设置mapper包日志级别为debug
          mapper: debug


ss:
  loginProcessingUrl: /sys/userLogin/login
  usernameParameter: username
  passwordParameter: password
  codeParameter: code
  permitAllList: /sys/userLogin/login, /permitAll, /*.html, /**/*.html, /**/*.css, /**/*.js
  anonymousList: /sys/userLogin/login, /login, /captchaImage, /profile/**, /webjars/**, /swagger-ui.html, /swagger-resources/**, /druid/**

jwt:
  tokenHeader: Authorization
  tokenPrefix: "Bearer "
  expiration: 300
