server:
  port: 1234
  servlet:
    context-path: /demo

spring:
  redis:
    host: 127.0.0.1
    password: foobared
    # 连接超时时间（毫秒）
    timeout: 10000
    # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0 select 0
    database: 0
    #
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idel: 8
        # 连接池中的最小空闲连接 默认 0
        min-idel: 0

