server:
  port: 1234
  servlet:
    context-path: /demo


# DataSource Config
spring:
  resources:
    static-locations: classpath:/static/,classpath:/views/
  datasource:
    driver-class-name: org.sqlite.JDBC
#    url: jdbc:sqlite::resource:static/sqlite/scott.db3
    url: jdbc:sqlite:E:/scott.db3
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.SQLiteDialect
    # 显示sql
    show-sql: true
    properties:
      hibernate:
        # 格式化输出sql
        #        format_sql: true
        hbm2ddl:
          auto: update # update, none, create

# 显示jpa的入参
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace