server:
  port: 1234
  servlet:
    context-path: /demo


# DataSource Config
spring:
  resources:
    static-locations: classpath:/static/,classpath:/views/
  datasource:
    driver-class-name: org.sqlite.JDBC
    # resource:static方式，必须配置spring.resources.static-locations
    url: jdbc:sqlite::resource:static/sqlite/scott.db3
    # absolute path win
    #    url: jdbc:sqlite:E:/scott.db3
    # absolute Like Unix
    #    url: jdbc:sqlite:/Users/huiye/Documents/scott.db3
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.SQLiteDialect
    # 显示sql
    show-sql: true
    properties:
      hibernate:
        # 格式化输出sql
        format_sql: true
        hbm2ddl:
          auto: none # update, none, create，TODO 如果创建好后，就用none。

# 显示jpa的入参
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace