server:
  port: 1234
  servlet:
    context-path: /demo

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
