server:
  port: 1234
  servlet:
    context-path: /food-merge/
    session:
      timeout: 3600

beetlsql:
  enabled: false
beetl:
  suffix: html
  templatesPath: templates

spring:
  # DataSource Config
  datasource:
    driver-class-name: org.h2.Driver
    # 数据准备好后，就把schema和data注释掉。
    #schema: classpath:db/schema-h2.sql
    #data:
    #  - classpath:db/data-h2-sys_user.sql
    #  - classpath:db/data-h2-fd.sql
    #  - classpath:db/data-h2-yyss.sql

    # mem 内存模式 # 通过mode设置数据库兼容模式
    # url: jdbc:h2:mem:test;MODE=Mysql
    # 硬盘模式 会自动创建xxx.mv.db
    url: jdbc:h2:E:/food-merge;MODE=Mysql
    username: root
    password: test
  h2:
    # 开启console 访问 默认false
    console:
      enabled: true
      settings:
        # 开启h2 console 跟踪 方便调试  默认 false
        trace: true
        # 允许console 远程访问 默认false
        web-allow-others: true
      #  h2 访问路径上下文
      path: /h2-console

mybatis:
  # 扫描xml的位置
  mapper-locations: classpath:/mappers/**/*Mapper.xml

logging:
  level:
    com:
      example:
        lewjun:
          # 设置mapper包日志级别为debug
          mapper: debug

